### PR TITLE
basic2extended

### PR DESCRIPTION
**Pull request by umlaeute**
support for writing AMBIX_EXTENDED files as AMBIX_BASIC

it the user calls `ambix_open(AMBIX_BASIC)`, but then sets an adaptor matrix (via `ambix_set_adaptormatrix()`), the library will actually write an `AMBIX_EXTENDED` file that can
be played back by applying the given adaptor matrix (so: while writing, the full ambisonics set as given by the user is automatically multiplied by the inverse of the matrix)

### CODE REVIEW

**Comment by umlaeute** [comment]
@kronihias this should allow you to store a reduced set by providing the full set and the reconstruction matrix. the usage is basically to `ambix_open(AMBIX_BASIC)` and then call `ambix_set_adaptormatrix()` (which was previously forbidden).

if this works for you, i would like to remove the `ambix_matrix_pinv()` function from the API (and the `ambix_matrix_multiply()` along with it)

**Comment by kronihias** [comment]
Sorry, it took me some time to test this..
The reduction using the library works fine for me.

However I would keep pinv in the API to allow the user to check whether 
inversion of the matrix works.
Where is the problem with keeping the function publicly available?

Best, Matthias

**Comment by umlaeute** [comment]
the answer to that is simple: cruft!

libambix is a library dedicated to read and write ambix files.
the more functions unrelated to this task are accumulated within the library (in the public interface), the harder it will become to maintain it.

there is a simple (though as of today undocumented) way to check whether the matrix in invertible: `ambix_set_adaptormatrix()` will fail with an `AMBIX_ERR_INVALID_MATRIX` if it is not. (this check obviously has a side-effect: it will effectively set an adaptor matrix if it is valid).

**Comment by kronihias** [comment]
Fair enough, agreed.

**Pull request closed without merging**
